version: '3.9'

services:
  app:
    container_name: sbar
    depends_on:
      - db
    restart: always
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules 
      - .:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}
    
  db:
    image: postgres:13-alpine
    container_name: sbar-db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}

